name: Build Python Wheels

on:
  workflow_call:

jobs:
  sdist:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build
        run: python -m pip install --upgrade pip build

      - name: Build sdist
        run: python -m build --sdist --outdir dist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: dist/*

  wheel:
    runs-on: ${{ matrix.runner }}
    needs: [sdist]
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-15
            arch: native
            skip: ''
          - runner: macos-15-intel
            arch: native
            skip: ''
          - runner: ubuntu-24.04
            arch: x86_64
            skip: ''
          - runner: ubuntu-24.04
            arch: i686
            skip: ''
          # - runner: ubuntu-24.04-arm
          # arch: armv7l
          - runner: ubuntu-24.04-arm
            arch: aarch64
            skip: ''
          - runner: ubuntu-24.04
            arch: s390x
            skip: ''
          - runner: ubuntu-24.04
            arch: ppc64le
            # skip: '*musllinux*'
    steps:
      - uses: actions/checkout@v4

      - name: Download sdist artifact
        uses: actions/download-artifact@v4
        with:
          name: wheels-sdist
          path: dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ runner.os == 'Linux' }}

      - name: Extract sdist
        run: |
          mkdir -p sdist
          tar -xzf dist/*.tar.gz -C sdist --strip-components=1
          ls -ahl sdist

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - run: uv tool install https://github.com/henryiii/cibuildwheel/archive/refs/heads/henryiii/feat/uvbuild.zip

      - run: cibuildwheel sdist
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_ARCHS_MACOS: native
          CIBW_SKIP: ${{ matrix.skip }}

      - run: ls -ahl wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.runner }}-${{ matrix.arch }}
          path: wheelhouse/*

  merge-wheel-artifact:
    runs-on: ubuntu-slim
    needs: ['sdist', 'wheel']
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheel
          pattern: wheels-*
